# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: pygments

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Recreation Challenges - Bayes Hack 2016
subtitle: Recreation Challenges

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/hackathon'

# Author/Organization info to be displayed in the templates
author:
  name: U.S. Department of the Interior
  url: http://usinterior.github.io/hackathon

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /hackathon/assets/img/DOI-logo.png
logoalt: US Department of the Interior

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Schedule
  url: ./schedule
  internal: true
- text: Projects
  url: ./projects
  internal: true
- text: Code of Conduct
  url: ./code-of-conduct
  internal: true


# Style Variables
brand_color: "#2cb34a"
